### PR TITLE
Adds configurable value for time off status request

### PR DESCRIPTION
**Pull request by jesseschutt**

### CODE REVIEW

**Comment by JeffreyHyer** [comment]
Thanks for adding that @jesseschutt, I'll tag a new release after merging.

**Comment by jesseschutt** [comment]
Thanks Jeffrey - Much appreciated :-)

**Comment by jesseschutt** [comment]
Wondering when you'll be able to tag this new release? I need to pull it in on a project :-)

**Comment by JeffreyHyer** [comment]
It's in the [v1.0.4](https://github.com/JeffreyHyer/bamboohr/releases/tag/v1.0.4) release. Running `composer update` should install the latest version if you've already installed the package. If not, `composer require jeffreyhyer/bamboohr` will do the trick.

**Comment by jesseschutt** [comment]
Sure enough! Thank you :-)

**Pull request merged**
